# Server Configuration
server.port=8081

# AWS RDS PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://hrms-postgres1.cxucu8ayu0hl.ap-south-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgresadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.security.user.name=admin
spring.security.user.password=devpassword123

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true